### ISSUE TITLE
Make the agent exporter configurable

### ISSUE THREAD

**Issue by dlmutart** [ScalaConsultants/mesmer#169]
I can't seem to find where the java agent can be configured to use different protocols and ports.  It would be nice if the java agent could take command line arguments like the core OpenTelemetry java agent does [https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md]  so we can at least set the otlp protocol and port used between the agent and the collector.

**Comment by lgajowy** [comment]
This is probably a too-late answer, but I will answer that either way :) 

Currently, you can only configure Mesmer via yaml config files tu turn features off/on. See the [reference.conf](https://github.com/ScalaConsultants/mesmer-akka-agent/blob/main/extension/src/main/resources/reference.conf) file as an example. Different protocols/ports usage can be configured when setting up the metric exporter. See the updated [README.md](https://github.com/ScalaConsultants/mesmer-akka-agent#exporter)  that shows how to setup a grpc exporter.

This will change however. The plan is to make Mesmer an otel agent extension. This way users will be able to configure it the same way as the otel agent and use mesmer's metrics on top of that. 

Please see this discussion: https://github.com/ScalaConsultants/mesmer-akka-agent/discussions/272
