### ISSUE TITLE
Example: Replace Mesmer Configuration SPI with sdk-autoconfigure from opentelemetry

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#339]
I found this: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure

I think it's the simplest way of configuring mesmer and we should promote it in our example. It will still be possible to configure the application using other ways (eg. SdkBuilder). It also eliminates the need for the Opentelemetry config loading spi and afaik automatically takes care of shutting down opentelemetry sdk when needed:

> The autoconfigure module registers Java shutdown hooks to shut down the SDK when appropriate.

**Comment by lgajowy** [comment]
I added it to the next release - @adamgadomski @worekleszczy please tell me if you disagree

**Comment by worekleszczy** [comment]
It's a good idea - it doesn't really change much for extension users, but it shows another good practice when working with `openTelemetry`
