### ISSUE TITLE
[Question] Is Mesmer supposed to work with google cloud exporter?

### ISSUE THREAD

**Issue by pulewicz** [ScalaConsultants/mesmer#389]
We' trying to use OpenTelemetry with Mesmer in our codebase, we would like to have both traces and metrics in Google Cloud.

The metrics work locally (we used the example from this repository), however when we switch to google cloud we get the following errors:

```
[otel.javaagent 2022-04-21 08:34:57:862 +0200] [PeriodicMetricReader-1] WARN io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter threw an Exception
[error] com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).; The set of resource labels is incomplete. Missing labels: (namespace task_id).
```

```
[error] [otel.javaagent 2022-04-21 08:35:12:320 +0200] [PeriodicMetricReader-1] WARN io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter threw an Exception
...
[error] Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
[error] 	at io.grpc.Status.asRuntimeException(Status.java:535)
[error] 	... 10 more
[error] Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (10240)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
[error] 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:245)
```

We're using the exporter from: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java

The short summary:
- Traces from OpenTelemetry with Google Cloud - works
- Traces from OpenTelemetry with Google Cloud + Mesmer metrics locally (`otlp` exporter) - works
- Traces from OpenTelemetry with Google Cloud + Mesmer metrics with Google Cloud (`google_cloud_monitoring` exporter) - doesn't work
- Just Google Cloud exporter (example app from https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java) - works

Questions:
1. Should Mesmer metrics work with the google cloud exporter?
2. If so, is there any additional configuration required on either side?

We can provide an example reproducing this problem based on the answers.

Regards,
Paweł Ulewicz.

**Comment by lgajowy** [comment]
> Should Mesmer metrics work with the google cloud exporter?

We haven't tried that, I think. But I think that it should be possible to run - Mesmer does not do any operations specific to a particular set of exporters afaik. It uses only otel API - the SDK part (exporters included) are up to the user.

> If so, is there any additional configuration required on either side?

I think the exporter might require some additional config. I've found a similar issue in the exporter and people suggested setting a Resource: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/139#issuecomment-1033801997. Maybe this is the solution here too?

> We can provide an example reproducing this problem based on the answers.

In case the above is not helpful, please provide the example - I'd be happy to take a deeper look.

Thanks!

**Comment by pulewicz** [comment]
You're right, this environment variable fixed the problem:

```
OTEL_RESOURCE_ATTRIBUTES=service.namespace=test-namespace,service.instance.id=test-instance-id
```

As for why it worked in the example: I pulled the latest changes with the fix that is not released yet. That's why it worked in the exporter example and not in our codebase.

Thanks for help!
