### ISSUE TITLE
(Tiny) Research: How to collect JVM Metrics from ZIO

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#424]
It seems that there's an effort to collect lots of Default-JVM-metrics in zio apps: [DefaultJvmMetrics](https://github.com/zio/zio/blob/series/2.x/core/jvm/src/main/scala/zio/metrics/jvm/DefaultJvmMetrics.scala). 

Thanks to issues #421, #422 and #423 we should be able to attach to all histograms, Gauges and Counters. Therefore it would be nice to see the JVM metrics being collected via opentelemetry too. 

Goal: 
- figure out how to turn on Jvm metrics collection. 
- if it works with few configuration needed, explain how to do it in mesmer documentation so that users can see those thanks to Mesmer as well

**Comment by ronaldSC-2022** [comment]
Hi @lgajowy, I can take / be assigned this Issue.

**Comment by lgajowy** [comment]
Welcome! Go ahead! :)

**Comment by ronaldSC-2022** [comment]
@lgajowy,

The write-up / research results are summarized in this GitHub Discussion: https://github.com/ScalaConsultants/mesmer/discussions/458

**Comment by lgajowy** [comment]
Thanks! All done - closing
