### ISSUE TITLE
Serialization issue with the GetActors command

### ISSUE THREAD

**Issue by pulewicz** [ScalaConsultants/mesmer#439]
Hi,

When we added Mesmer to our akka app, we get the following error:

```
logger_name: "akka.remote.artery.Encoder"
message: "Failed to serialize message [io.scalac.mesmer.extension.service.ActorTreeService$Command$GetActors]."
sourceActorSystem: "api"
sourceThread: "api-akka.remote.default-remote-dispatcher-9"
stack_trace: "akka.serialization.DisabledJavaSerializer$JavaSerializationException: Attempted to serialize message using Java serialization while `akka.actor.allow-java-serialization` was disabled. Check WARNING logs for more details."
```

And the following warning:

```
logger_name: "akka.serialization.DisabledJavaSerializer"
message: "Outgoing message attempted to use Java Serialization even though `akka.actor.allow-java-serialization = off` was set! Message type was: [class io.scalac.mesmer.extension.service.ActorTreeService$Command$GetActors]"
sourceActorSystem: "api"
sourceThread: "api-akka.remote.default-remote-dispatcher-9"
```

Can it be caused by the fact that `GetActors` command (and the other commands) don't extend`io.scalac.mesmer.extension.SerializableMessage`? The binding is only for this trait: 

```
"io.scalac.mesmer.extension.SerializableMessage" : "jackson-cbor",
```

We're using Mesmer `0.6.0` and Akka `2.6.18`, we have a cluster of 3 nodes deployed using kubernetes on Google Cloud. Unfortunately we're not able to provide an example reproducing the issue (also it doesn't happen all the time, only during a bigger load on the app).

Regards,
Paweł Ulewicz.

**Comment by lgajowy** [comment]
@pulewicz I think you seem to be on the right track. Do you feel like creating a PR fixing this issue? :) 

Either way I included it in our next release so that it's solved - looks like a low hanging fruit (hope it is).

**Comment by lgajowy** [comment]
There is no extension anymore - closing
