### ISSUE TITLE
Remove EventBus from mesmer-akka-core

### ISSUE THREAD

**Issue by ghost** [ScalaConsultants/mesmer#460]
After discussion with @lgajowy, the purpose of this Discovery Ticket is to:

- Determine if we can remove `EventBus` (https://github.com/ScalaConsultants/mesmer/blob/main/core/src/main/scala/io/scalac/mesmer/core/event/EventBus.scala#L20-L32) from mesmer-akka-core.

- If the answer is **yes**, then I will create a "follow-up-kanban-ticket" for implementing this "EventBus removal from the mesmer-akka-core code".

**Comment by lgajowy** [comment]
Isn't https://doc.akka.io/api/akka/2.4/akka/typed/EventStream.html or DistributedPubSub an akka ready-to-use equivalent of the EventBus we have customly developed?
