### ISSUE TITLE
Fix Grafana Dashboards

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#482]
After changing some metric names/types (eg. from Gauge to Histograms) some of the Grafana dashboards stopped working. The task is to reinstate the graphs.

**Comment by lgajowy** [comment]
The dashboards are here: 
example/docker/dashboards/akka-persistence.json
example/docker/dashboards/akka-cluster.json
example/docker/dashboards/akka-http.json

Http shows metrics from opentelemetry Instrumentations so it should be all good. We for sure changed persistence metrics. Not sure about Cluster - to be checked as well.

**Comment by guda249** [comment]
I would like to pick this up

**Comment by lgajowy** [comment]
Sure, thanks! :)

**Comment by guda249** [comment]
I have followed example readme, able to see the metrics getting populated in http and cluster graph except for persistence dashboard. I couldn't find any metric in promethus for example `promexample_akka_persistence_persistent_event_sum`. Am i missing anything ?

**Comment by lgajowy** [comment]
Do you run any query so that akka persistence is actually used? Some of the metrics initialize lazily on the first use.  

> promexample_akka_persistence_persistent_event_sum

For that I think you can use `mesmer_akka_persistence_event_time_count` instead (means the same thing so we removed the latter).
