### ISSUE TITLE
zio_fibers_started is always 0

### ISSUE THREAD

**Issue by lgajowy** [ScalaConsultants/mesmer#539]
promexample_mesmer_zio_forwarded_zio_fiber_started

To be fixed. No idea why yet.

**Comment by ptrdom** [comment]
Checked this locally on https://github.com/ScalaConsultants/mesmer/pull/612 branch, prometheus does return this metric with a non-zero value.

**Comment by lgajowy** [comment]
Indeed not an issue. Closing.
