### ISSUE TITLE
Follow-up on `AggregationTemporality` for `agent-for-testing` issue

### ISSUE THREAD

**Issue by ptrdom** [ScalaConsultants/mesmer#618]
Currently we are building `agent-for-testing` on our own with change to `AggregationTemporality` rolled back from `delta` to `cumulative`.

We proposed to make this configurable in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7902, let's see how it goes and keep in mind follow-up actions based on outcome.

**Comment by lgajowy** [comment]
The PR that allows configuring the aggregation temporality was merged: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7904/files 

It should be ready to use in otel 1.24 version
