### ISSUE TITLE
Suffixes duplicates in prometheus exporter metrics

### ISSUE THREAD

**Issue by mBut** [ScalaConsultants/mesmer#633]
If you enable the agent to expose metrics using Prometheus `-Dotel.metrics.exporter=prometheus` then exporting metrics have a wrong naming scheme 

```
100# TYPE mesmer_akka_actor_actors_created_total_total counter
# HELP mesmer_akka_actor_actors_created_total_total Amount of actors created measured from Actor System start
mesmer_akka_actor_actors_created_total_total{otel_scope_name="mesmer"} 53.0 1678204428403
# TYPE mesmer_akka_actor_stashed_messages_total_total counter
# HELP mesmer_akka_actor_stashed_messages_total_total
mesmer_akka_actor_stashed_messages_total_total{otel_scope_name="mesmer",actor_path="/system",actor_system="accounts"} 4.0 1678204428403
# TYPE mesmer_akka_cluster_node_down_total_total counter
# HELP mesmer_akka_cluster_node_down_total_total Counter for node down events
mesmer_akka_cluster_node_down_total_total{otel_scope_name="mesmer",node="akka://accounts@127.0.0.1:2551"} 0.0 1678204428403
# TYPE mesmer_akka_actor_sent_messages_total_total counter
# HELP mesmer_akka_actor_sent_messages_total_total
mesmer_akka_actor_sent_messages_total_total{otel_scope_name="mesmer",actor_path="/system",actor_system="accounts"} 301.0 1678204428403
```

This is happening because OTLP metrics are defined using Prometheus naming scheme. The same behaviour cannot be observed when the metrics are exported using OTLP exporter because of the trimming. The suffixes must be dropped everywhere to ensure the correct metric names.

The collector already supports normalisation for Prometheus metrics but this feature is still in alpha stage and needs to be explicitly enabled. See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#metric-name

**Comment by ptrdom** [comment]
@lgajowy Is the fix here to check for `-Dotel.metrics.exporter=prometheus` being set and not add suffixes in that case?

**Comment by lgajowy** [comment]
Not sure. In general, that would be similar to what I think they try to achieve in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#metric-name 

but given that not everyone uses the collector, maybe for our use case it makes sense to just change metric names to not have the _total suffix at all? wdyt?

**Comment by ptrdom** [comment]
Yeah, I think we should stick to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md, and what we are doing now is https://prometheus.io/docs/practices/naming/, so let's drop those suffixes.
